apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-hello-kube-deployment
  labels:
    app: hello-kube
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000      
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-hello-kube-config
          env:
          - name: NODE_ENV
            value: {{ .Values.env.NODE_ENV }}
