apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless-external-secret
spec:
  refreshInterval: 1h #Refresh Interval to refresh the secrets

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster

  target:
    name: akeyless-secret-example # Name for the secret to be created on the cluster
    creationPolicy: Owner

  data:
    - secretKey: firstsecret # Key given to the secret to be created on the cluster
      remoteRef:
        key: /MyFirstSecret # Full path of the secret on Akeyless
    - secretKey: secondsecret # Key given to the secret to be created on the cluster
      remoteRef:
        key: /MySecondSecret # Full path of the secret on Akeyless
